### PR TITLE
fixed contact page mobile view

### PR DESCRIPTION
**Pull request by khanh-do**
### Describe the problem being solved:
The original design requests were modified as per discussion with @hmichele. The updated design change requests for the mobile view are:
- [x] Decrease line spacing where needed.
- [x] Left justify the desired text.

### Impacted areas in the application: 
The styling of the text, particularly for the mobile views.

List general components of the application that this PR will affect: 
* Contact

Before:
Screenshot from 2019-11-01 03-38-48

Screenshot from 2019-11-01 03-40-00

Screenshot from 2019-11-01 03-40-23

After:
Screenshot from 2019-11-01 03-36-49

Screenshot from 2019-11-01 03-37-12

Screenshot from 2019-11-01 03-37-30

PR checklist
- [x] I included  a screenshot for FE changes
- [x] I have linked the PR to a Zenhub ticket
- [x] I have checked for merge conflicts
- [x] I have run the [prettier](https://prettier.io/) command `make pretty`

### CODE REVIEW

**Comment by khanh-do** [comment]
Thank you for the review, Dan. I can change it back to the staging view for the larger desktop sizes if needed. Michele and I prefer this branch view for the larger desktop as well as for the mobile view. The signature text lines, below, are closer together. It makes sense to me to space these lines closer together because they are a grouping (all lines describe Kim).

Kim Wright, MBA, U.S. Army Veteran                
Foster Youth Alumna
Founder, Young Masterbuilders in Motion
Email: Founder@theymim.org |&nbsp;Phone: 773.941.1200

Staging:
Screenshot from 2019-11-08 12-11-01

This Branch:
Screenshot from 2019-11-08 12-11-08

I defer to @dkaplan88 and @hmichele for the final decision. Please let me know and I'll work on the fix or not. Thank you.

**Comment by khanh-do** [comment]
One more thought: With the original form, the design change by this branch did not result the separation of the "Phone" and the number. With the new changes added by the Google form design, this resulted in the separation of "Phone" and the number. Perhaps this fix could be done in a new ticket. Perhaps we could separate the Email and Phone into separate lines, so the mobile views would look better as well.

**Comment by hmichele** [comment]
@khanh-do Please keep all views (mobile, desktop, tablet) consistent and go with the branch view where the signature text lines are closer together.  Thanks.

**Comment by hmichele** [comment]
@dkaplan88 I believe you were referring to the left justified issue.  It only shows up that way on desktop and tablet view, but not mobile.

**Pull request merged**
